---
env:
  browser: true
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
  sourceType: module
plugins:
  - prettier
extends:
  - eslint:recommended
  - plugin:prettier/recommended
rules:
  prettier/prettier: error
